[pytest]
; json格式的
; addopts=-s --alluredir report
; html格式的
addopts = -v -s 
        --html=report/html_report.html 
        --self-contained-html
        --alluredir=report/allure-report
        --clean-alluredir
testpaths=./script
python_files=test*.py
python_classes=Test*
python_functions=test*
; All相关配置
; pytest --alluredir=report/allure-results 执行命令
; allure_report_dir = report/allure-report
; allure_clean_results = true